apiVersion: apps/v1
kind: Deployment
metadata:
  name: vampi
  namespace: bctl-app
  labels:
    app: vampi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vampi
  template:
    metadata:
      labels:
        app: vampi
    spec:
      containers:
        - name: vampi
          image: erev0s/vampi:latest
          ports:
            - containerPort: 5000
          env:
            - name: vulnerable
              value: "1"
            - name: tokentimetolive
              value: "9999"
