apiVersion: v1
kind: Service
metadata:
  name: vampi-svc
  namespace: bctl-app
spec:
  selector:
    app: vampi
  type: NodePort
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 31500
